name = "threat-triage"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "threat-triage-db"
database_id = "f75d5c10-6dd8-46a7-98d8-d2d178c87c6e"

[[vectorize]]
binding = "VECTORIZE"
index_name = "triage-embeddings"

[ai]
binding = "AI"
